name: Continuous Integration

on:
  push:
    branches-ignore:
      - main

jobs:
  pre-commit:
    permissions:
      contents: read
    uses: ./.github/workflows/pre-commit.yml
    with:
      skip: "no-commit-to-branch"
